#
# OTG infrastructure and transceiver drivers
#

ccflags-$(CONFIG_USB_DEBUG)		:= -DDEBUG
ccflags-$(CONFIG_USB_GADGET_DEBUG)	+= -DDEBUG

# transceiver drivers
obj-$(CONFIG_USB_MSM_OTG_72K)	+= msm72k_otg.o
