ifeq ($(CONFIG_ARCH_MSM7X30),y)
  obj-$(CONFIG_MSM_CAMERA) += msm_camera-7x30.o
endif
obj-$(CONFIG_MSM_CAMERA) += msm_axi_qos.o

obj-$(CONFIG_MSM_CAMERA) += gemini_8x60/
obj-$(CONFIG_MSM_CAMERA_FLASH) += flash_8x60.o

obj-$(CONFIG_ARCH_MSM7X30) += msm_vfe_7x30.o msm_io_7x30.o msm_vpe1_7x30.o

obj-$(CONFIG_OV8810) += ov8810.o
obj-$(CONFIG_S5K3H1GX) += s5k3h1gx.o s5k3h1gx_reg.o
